services:
  nginx:
    image: webdevops/php-nginx:8.4-alpine
    restart: unless-stopped
    networks:
      proxy:
        aliases:
          - mc-nginx
    volumes:
      - type: bind
        source: ./vhost.conf
        target: /opt/docker/etc/nginx/vhost.conf
        read_only: true
      - type: bind
        source: /opt/minecraft/backups
        target: /app/backup
        read_only: true
      - type: bind
        source: /opt/minecraft/modpacks
        target: /app/modpack
        read_only: true
    labels:
      traefik.enable: "true"
      traefik.http.routers.mc-files.rule: Host(`files.off-topic.chat`)
      traefik.http.routers.mc-files.service: mc-files
      traefik.http.services.mc-files.loadbalancer.server.url: http://mc-nginx:80

networks:
  proxy:
    name: ovh-proxy_default
    external: true